### ISSUE TITLE
Log in with "midlertidigt kodeord"

### ISSUE THREAD

**Issue by everhoej** [Notalib/LYT#500]
Today it is possible to log in with a "midlertidigt kodeord" on E17 Direkte without being asked to change it or being directed to E17 to change it.  This way the user can actually log in and listen to books with a "midlertidigt kodeord".

The right flow would be to direct the user who log in with a "midlertidigt kodeord", to a new page on the player where they can change their password.

**Comment by saebekassebil** [comment]
Not a player issue any longer, since the login page has been redirected to Nota.dk
